### ISSUE TITLE
Does not output anything

### ISSUE THREAD

**Issue by AdamAtomus** [TheSmugGod/qb2ox#1]
When running the script, the script does not output anything.
![image](https://github.com/TheSmugGod/qb2ox/assets/42122290/b85e935e-0b30-4992-8e99-9d18d3ba68d8)

**Comment by TheSmugGod** [comment]
can you show what the input.txt looks like ?

**Comment by AdamAtomus** [comment]
It's the same as the one provided on repository , I've tested my own, and the one that is already included in the input.txt
![image](https://github.com/TheSmugGod/qb2ox/assets/42122290/0859ddd4-e378-4c63-8104-0cd4d6e6c25e)

**Comment by TheSmugGod** [comment]
thanks for reporting the issue, i have fixed it, please redownload the qb2ox.py and let me know if the same issue is there
